//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosStoneNfce.API.Portal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PosStoneNfce.API.Portal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistência ao agendar a videoconferência..
        /// </summary>
        internal static string ErroAgendarVideoconferencia {
            get {
                return ResourceManager.GetString("ErroAgendarVideoconferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistência ao buscar os horários..
        /// </summary>
        internal static string ErroBuscarHorarios {
            get {
                return ResourceManager.GetString("ErroBuscarHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistência ao buscar o pedido..
        /// </summary>
        internal static string ErroBuscarPedido {
            get {
                return ResourceManager.GetString("ErroBuscarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistência ao buscar as solicitações..
        /// </summary>
        internal static string ErroBuscarSolicitacoes {
            get {
                return ResourceManager.GetString("ErroBuscarSolicitacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistência ao buscar o voucher..
        /// </summary>
        internal static string ErroBuscarVoucher {
            get {
                return ResourceManager.GetString("ErroBuscarVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistência ao importar o documento..
        /// </summary>
        internal static string ErroImportarDocumento {
            get {
                return ResourceManager.GetString("ErroImportarDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistência na nova solicitação..
        /// </summary>
        internal static string ErroNovaSolicitacao {
            get {
                return ResourceManager.GetString("ErroNovaSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistência ao gerar o token..
        /// </summary>
        internal static string ErrorToken {
            get {
                return ResourceManager.GetString("ErrorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível buscar as permissões de empresas do usuário..
        /// </summary>
        internal static string ErroUsuarioPermissoesEmpresa {
            get {
                return ResourceManager.GetString("ErroUsuarioPermissoesEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id inválido..
        /// </summary>
        internal static string IdInvalido {
            get {
                return ResourceManager.GetString("IdInvalido", resourceCulture);
            }
        }
    }
}
